name: npm publish
on:
  release:
    types: [published]
jobs:
  build:  
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sika7'
      - run: |
          npm run test
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
